version: "3.9"

services:
    python: 
        container_name: fastapi-cadastro
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/app
        networks:
            - private
        depends_on: 
            - db
    
    db:
        image: postgres:alpine
        container_name: db
        ports: 
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - private
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: '123456'
            POSTGRES_DB: fastapi_database
volumes:
    pgdata:

networks: 
    private: